<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>CanDO - Terms of use</title>
</head>
<div class="container">
  <div class="header"><?php include('header.php'); ?></div>
  <div class="content">
  	<div style="margin-left:80px;" >
      <h3>Overview</h3>
<p>The following are terms of a legal agreement between you and CanDO. By accessing, browsing, or using this Web site, you acknowledge that you have read, understood, and agree to be bound by these terms and to comply with all applicable laws and regulations, including export and re-export control laws and regulations. If you do not agree to these terms, please do not use this Web site. 
</p>
<p>CanDO may, without notice to you, at any time revise these Terms of Use and any other information contained in this Web site by updating this posting. CanDO may also make improvements or changes in the products, services, or programs described in this site at any time without notice.
</p><h3>General</h3>
<p>This Web site contains proprietary notices and copyright information, the terms of which must be observed and followed.  Please see the tab entitled “Copyright and trademark information” for related information.
</p>
<p>This site and all content in this site may not be copied, reproduced, republished, uploaded, posted, transmitted, distributed, or used for the creation of derivative works without CanDO's prior written consent, except that CanDO grants you non-exclusive, non-transferable, limited permission to access and display the Web pages within this site, solely on your computer and for your personal, non-commercial use of this Web site.  This permission is conditioned on your not modifying the content displayed on this site, your keeping intact all copyright, trademark, and other proprietary notices, and your acceptance of any terms, conditions, and notices accompanying the content or otherwise set forth in this site.  Notwithstanding the foregoing, any software and other materials that are made available for downloading, access, or other use from this site with their own license terms, conditions, and notices will be governed by such terms, conditions, and notices.
</p>
<p>Your failure to comply with the terms, conditions, and notices on this site will result in automatic termination of any rights granted to you, without prior notice, and you must immediately destroy all copies of downloaded materials in your possession or control.  Except for the limited permission in the preceding paragraph, CanDO does not grant you any express or implied rights or licenses under any patents, trademarks, copyrights, or other proprietary or intellectual property rights.  You may not mirror any of the content from this site on another Web site or in any other media.
</p><h3>Certain disclaimers</h3>
<p>Information on this Web site is not promised or guaranteed to be correct, current, or complete, and this site may contain technical inaccuracies or typographical errors. CanDO assumes no responsibility (and expressly disclaims responsibility) for updating this site to keep information current or to ensure the accuracy or completeness of any posted information.  Accordingly, you should confirm the accuracy and completeness of all posted information before making any decision related to any services, products, or other matters described in this site. 
</p>
<p>CanDO provides no assurances that any reported problems will be resolved by CanDO, even if CanDO elects to provide information with the goal of addressing a problem.
</p><h3>Forward-looking and cautionary statements</h3>
<p>Except for historical information and discussions, statements set forth throughout this web site may constitute forward-looking statements within the meaning of the Private Securities Litigation Reform Act of 1995 or other applicable laws.  These statements involve a number of risks, uncertainties, and other factors that could cause actual results to differ materially, as discussed in the company's filings with the U.S. Securities and Exchange Commission.  See the “SEC filings” tab under “Investor relations” on this Web site for copies of such filings.
</p><h3>Confidential information</h3>
<p>CanDO does not want to receive confidential or proprietary information from you through our Web site. Please note that any information or material sent to CanDO will be deemed NOT to be confidential. By sending CanDO any information or material, you grant CanDO an unrestricted, irrevocable license to copy, reproduce, publish, upload, post, transmit, distribute, publicly display, perform, modify, create derivative works from, and otherwise freely use, those materials or information.  You also agree that CanDO is free to use any ideas, concepts, know-how, or techniques that you send us for any purpose. However, we will not release your name or otherwise publicize the fact that you submitted materials or other information to us unless: (a) we obtain your permission to use your name; or (b) we first notify you that the materials or other information you submit to a particular part of this site will be published or otherwise used with your name on it; or (c) we are required to do so by law.  Personally-identifiable information that you submit to CanDO for the purpose of receiving products or services will be handled in accordance with our privacy policies.  Please see the tab entitled “Privacy” for information regarding CanDO’s privacy policies.
</p><h3>U.S. government restricted rights</h3>
<p>CanDO provides the software downloaded from this Web site to U.S. Government users with “RESTRICTED RIGHTS." Use, reproduction, or disclosure is subject to the restrictions set forth in CanDO’s GSA ADP Schedule contract.
</p><h3>Global availability</h3>
<p>Information CanDO publishes on the World Wide Web may contain references or cross references to CanDO products, programs and services that are not announced or available in your country. Such references do not imply that CanDO intends to announce or make available such products, programs, or services in your country.  Please consult your local CanDO business contact for information regarding the products, programs, and services that may be available to you.
</p><h3>Business relationships</h3>
<p>This Web site may provide links or references to non-CanDO Web sites and resources.  CanDO makes no representations, warranties, or other commitments whatsoever about any non-CanDO Web sites or third-party resources (including any Lenovo Web site) that may be referenced, accessible from, or linked to any CanDO site. A link to a non-CanDO Web site does not mean that CanDO endorses the content or use of such Web site or its owner.  In addition, CanDO is not a party to or responsible for any transactions you may enter into with third parties, even if you learn of such parties (or use a link to such parties) from an CanDO site. Accordingly,  you acknowledge and agree that CanDO is not responsible for the availability of such external sites or resources, and is not responsible or liable for any content, services, products, or other materials on or available from those sites or resources.
</p>
<p>When you access a non-CanDO Web site, even one that may contain the CanDO-logo, please understand that it is independent from CanDO, and that CanDO does not control the content on that CanDO site. It is up to you to take precautions to protect yourself from viruses, worms, trojan horses, and other potentially destructive programs, and to protect your information as you deem appropriate.
</p><h3>Linking to this site</h3>
<p>All links to this Web site must be approved in writing by CanDO, except that CanDO consents to links in which the link and the pages that are activated by the link do not:  (a)  create frames around any page on this Web site or use other techniques that alter in any way the visual presentation or appearance of any content within this site; (b) misrepresent your relationship with CanDO; (c)  imply that CanDO approves or endorses you, your Web site, or your service or product offerings; and (d) present false or misleading impressions about CanDO or otherwise damage the goodwill associated with the CanDO name or trademarks.  As a further condition to being permitted to link to this site, you agree that CanDO may at any time, in its sole discretion, terminate permission to link to this Web site.  In such event, you agree to immediately remove all links to this Web site and to cease using any CanDO trademark.

</p><h3>Translations</h3>
<p>Certain text in this Web site may be made available in languages other than English.  Text may be translated by a person or solely by computer software with no human intervention or review.   These translations are provided as a convenience to you, and CanDO makes no representations or commitments regarding the accuracy or completeness of the translation, whether or not computer-generated or performed by a person.  Please see the below Disclaimer of Warranty for additional conditions.
</p><h3>DISCLAIMER OF WARRANTY</h3>
<p>USE OF THIS SITE IS AT YOUR SOLE RISK.  ALL MATERIALS, INFORMATION, PRODUCTS, SOFTWARE, PROGRAMS, AND SERVICES ARE PROVIDED "AS IS," WITH NO WARRANTIES OR GUARANTEES WHATSOEVER.  CanDO EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT PERMITTED BY LAW ALL EXPRESS, IMPLIED,  STATUTORY, AND OTHER WARRANTIES, GUARANTEES, OR REPRESENTATIONS, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY AND INTELLECTUAL PROPERTY RIGHTS.  WITHOUT LIMITATION, CanDO MAKES NO WARRANTY OR GUARANTEE THAT THIS WEB SITE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE.
</p>
<p>YOU UNDERSTAND AND AGREE THAT IF YOU DOWNLOAD OR OTHERWISE OBTAIN MATERIALS, INFORMATION, PRODUCTS, SOFTWARE, PROGRAMS, OR SERVICES, YOU DO SO AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGES THAT MAY RESULT, INCLUDING LOSS OF DATA OR DAMAGE TO YOUR COMPUTER SYSTEM.
</p>
<p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.
</p><h3>LIMITATION OF LIABILITY</h3>
<p>IN NO EVENT WILL CanDO BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY TYPE WHATSOEVER RELATED TO OR ARISING FROM THIS WEB SITE OR ANY USE OF THIS WEB SITE, OR OF ANY SITE OR RESOURCE LINKED TO, REFERENCED, OR ACCESSED THROUGH THIS WEB SITE, OR FOR THE USE OR  DOWNLOADING OF, OR ACCESS TO,  ANY MATERIALS, INFORMATION, PRODUCTS, OR SERVICES, INCLUDING, WITHOUT LIMITATION, ANY LOST PROFITS, BUSINESS INTERRUPTION, LOST SAVINGS OR LOSS OF PROGRAMS OR OTHER DATA, EVEN IF CanDO IS EXPRESSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THIS EXCLUSION AND WAIVER OF LIABILITY APPLIES TO ALL CAUSES OF ACTION, WHETHER BASED ON CONTRACT, WARRANTY, TORT, OR ANY OTHER LEGAL THEORIES.
</p>
<p>Additional or different terms, conditions, and notices may apply to specific materials, information, products, software, and services offered through this Web site. In the event of any conflict, such additional or different terms, conditions, and notices will prevail over these Terms of Use. Please see the applicable agreement or notice.
</p>
    </div>
  </div>
  <!--<div class="footer"><?php include('footer.php'); ?>--></div>
</div>
<body>
</body>
</html>